import { useEffect, useState } from 'react';
import type { Catalog, Detail } from './data/types';
import { shardOf } from './data/shard';

/**
 * The species catalog is generated by scripts/build-catalog.ts into public/data/.
 * The small index loads at start-up; the heavier per-species details load per shard when a card needs them.
 * The service worker caches both for offline use.
 */
const base = import.meta.env.BASE_URL;

let catalogPromise: Promise<Catalog> | null = null;
export function loadCatalog(): Promise<Catalog> {
  catalogPromise ??= fetch(`${base}data/catalog.json`).then((r) => {
    if (!r.ok) throw new Error(`catalog ${r.status}`);
    return r.json() as Promise<Catalog>;
  });
  catalogPromise.catch(() => (catalogPromise = null)); // allow a retry
  return catalogPromise;
}

export function useCatalog(): { catalog: Catalog | null; error: boolean; retry: () => void } {
  const [catalog, setCatalog] = useState<Catalog | null>(null);
  const [error, setError] = useState(false);
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    let live = true;
    setError(false);
    loadCatalog()
      .then((c) => live && setCatalog(c))
      .catch(() => live && setError(true));
    return () => {
      live = false;
    };
  }, [attempt]);
  return { catalog, error, retry: () => setAttempt((a) => a + 1) };
}

const shardCache = new Map<number, Promise<Record<string, Detail>>>();
const loaded = new Map<string, Detail>();

function loadShard(i: number): Promise<Record<string, Detail>> {
  let pr = shardCache.get(i);
  if (!pr) {
    pr = fetch(`${base}data/details/${i}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`details ${r.status}`);
        return r.json() as Promise<Record<string, Detail>>;
      })
      .then((d) => {
        for (const [id, det] of Object.entries(d)) loaded.set(id, det);
        return d;
      });
    pr.catch(() => shardCache.delete(i));
    shardCache.set(i, pr);
  }
  return pr;
}

export async function loadDetail(id: string): Promise<Detail | undefined> {
  const c = await loadCatalog();
  return (await loadShard(shardOf(id, c.shards)))[id];
}

/** Detail for one species; undefined while loading (or if missing). */
export function useDetail(id: string | undefined): Detail | undefined {
  const [detail, setDetail] = useState<Detail | undefined>(id ? loaded.get(id) : undefined);
  useEffect(() => {
    if (!id) return setDetail(undefined);
    const hit = loaded.get(id);
    setDetail(hit);
    if (hit) return;
    let live = true;
    loadDetail(id)
      .then((d) => live && setDetail(d))
      .catch(() => {
        /* offline and not cached: card shows without details */
      });
    return () => {
      live = false;
    };
  }, [id]);
  return detail;
}
